language: elixir

matrix:
  include:
    - elixir: 
        - 1.6.6
      otp_release:
        - 19.3
        - 20.3
        - 21.3
    - elixir: 
        - 1.7.4
        - 1.8.2
      otp_release:
        - 19.3
        - 20.3
        - 21.3
        - 22.0
    - elixir: 
        - 1.9.0
      otp_release:
        - 20.3
        - 21.3
        - 22.0


script:
  - "MIX_ENV=test mix do deps.get, deps.compile, credo --strict, test"
